name: Test Traceable AST Init And Run Action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  InitAndRunAstScan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init and run scan action
        uses: Traceableai/ast-action@main
        with:
          step_name: 'init and run'
          client_scan_token: "89duuMVedPJO-TXXW9L77gOpW8hfaIBqgtY147XLWlCt6"
          cli_version: 'latest'
          traffic_env: 'crapi-demo1'
          traceable_server: "api.traceable.ai"
      - name: Stop Scan
        if: always()
        uses: Traceableai/ast-action@main
        with:
          step_name: 'stop'
          client_scan_token: "89duuMVedPJO-TXXW9L77gOpW8hfaIBqgtY147XLWlCt6"
          traffic_env: 'crapi-demo1'
          traceable_server: "api.traceable.ai"
  functionalTest:
    runs-on: ubuntu-20.04
    steps:
      - name: Run a loop as functional test
        run: |
          for ((i=1;i<=100;i++)); 
          do 
             echo $i
          done
